#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Mar 23 01:55:00 2020

@author: atle
"""

import sys
import time

# CLASSES

# Player Class
class Player(object):
    """A few attributes"""
    def __init__(self):
        self.name = ""
        
orbit = Player()


# LEVELS


# start
def start(liste):
    player_name = setup_name()
    text_medium("\nDarknes reign in this mysterious place")
    text_fast(f"\nWhat do your soul desire to do here?")
    print() # space
    print("\n1 Walk around without purpose and get to know the unknown")
    print("\n2 Howl into the dark")
    print("\n3 Do nothing")
    print('\n4 #4')
    
    choices = ['1', '2', '3', '4']
    pick = selected(choices)
    
    if pick == "1":
        if "item1" in liste:
            print("'Item 1' is in the list")
            print("loading...")
            time.sleep(2)
            scene1(liste)
        else:
            print("'Item 1' is not in the list")
            print(liste)
            time.sleep(2)
            start(liste)
            
    elif pick == "2":
        print("\nItem 1 in front of you")
        print("\nWhat do you do:")
        print("\nPick item 1 (1)")
        print("\nWalk away (2)")
        choices = ['1', '2']
        pick = selected(choices)
        if pick == "1":
            liste.append("item1")
            start(liste)
        else:
            print("You didn't pick the item1")
            return start(liste)
        
    elif pick == "3":
        print(liste)
        print("You don't need any distractions")
        print("We understand that")
        print("You can stay here as long as you want")
        
    elif pick == "4":
        print("Go to scene 1")
        time.sleep(1)
        scene1(liste, player_name)
        
        

def scene1(liste, player_name):    
    print("Hey", name)
    print(liste)


# GAME ENGINE

# Choices
def selected(choices):
    
    select = input('\n? ')
    if select in choices:
        return select
    elif select == 'q':
         exit(0)
    else:
        print('Wrong input')
        return selected(choices)
 
# Asks for players name
def setup_name():
    text1 = "Hello there stranger, who are you?"
    for i in text1:
        sys.stdout.write(i)
        sys.stdout.flush()
        time.sleep(0.05)    
    orbit.name = input("\n> ")
    name = orbit.name
    return name

# Typewriter effects
def text_fast(str):
    for i in str:
        sys.stdout.write(i)
        sys.stdout.flush()
        time.sleep(0.1)  
        
def text_medium(str):
    for i in str:
        sys.stdout.write(i)
        sys.stdout.flush()
        time.sleep(0.16)
        
def text_slow(str):
    for i in str:
        sys.stdout.write(i)
        sys.stdout.flush()
        time.sleep(0.3)        
# Empty list
liste = [] 

# START GAME

# start function including liste and setup
start(liste)
